# Site settings
title: Przyjaciele Szkoły Muzycznej w Świdnicy
email: info@muzyczna.org
description: >
  Stowarzyszenie jest zrzeszeniem osób fizycznych, zawiązanym dla wspierania działalności statutowej Państwowej Szkoły
  Muzycznej I st. im. Ludomira Różyckiego w Świdnicy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://muzyczna.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
google_play: 'GDGX'
google_plus_com: '109485346959707049693'  # Community link
google_plus_per: '+GDGManagua'  #Personal link
facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: false
disqus_shortname: ''

# Build settings
markdown: kramdown
